// <auto-generated />
namespace Data.EntityInformation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcols : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcols));
        
        string IMigrationMetadata.Id
        {
            get { return "201609181442435_add cols"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
